### ISSUE TITLE
Day of month was "?" and day of week was specified, came across error "ValueError: day is out of range for month"

### ISSUE THREAD

**Issue by mattdavis1783** [beemhq/aws-cron-parser#18]
We were able to replicate the error using the following code:

`import datetime`
`from pyawscron import AWSCron`

`cron = '0 9 ? * 2 *'`
`a = AWSCron(cron)`
`now = datetime.datetime(2021, 8, 31, 21, 0, 0, tzinfo=datetime.timezone.utc)`
`a.occurrence(now).next()`
`base = a.occurrence(now).next()`
`print(base)`
`base = a.occurrence(base).next()`
`print(base)`
`base = a.occurrence(base).next()`
`print(base)`
`base = a.occurrence(base).next()`
`print(base)`
`base = a.occurrence(base).next()`
`print(base)`

When you run the above code you should get `ValueError: day is out of range for month`

**Comment by vinhtnguyen** [comment]
I'm sorry but this is a JavaScript package. I'm not sure why you are using it in Python.
FWIW, I tried your cron and it works: https://runkit.com/embed/zvmycs9yjdm6

**Comment by mattdavis1783** [comment]
Apologies, I was referring to the python version of the package ([repo here](https://github.com/pitchblack408/pyawscron/issues)), sorry for the confusion.
