### ISSUE TITLE
*L* doesnt work as expected on daysOfWeek

### ISSUE THREAD

**Issue by farhancs91** [beemhq/aws-cron-parser#2]
When running the below command:
var awsCronParser = require("aws-cron-parser")
const cron = awsCronParser.parse("15 10 ? * 6L 2002-2025");

Output:
daysOfMonth: null
daysOfWeek: [67]
hours: [10]
minutes: [15]
months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
years: [2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, …]

daysOfWeek should be last friday of every month. But as per the above output, days of the week is 67 which is not expected.

**Comment by vinhtnguyen** [comment]
Thank you for reporting this bug. It is fixed now with version 1.1.4
