### ISSUE TITLE
[typescript] Provide d.ts file in the package deployed to npm

### ISSUE THREAD

**Issue by mlippens** [beemhq/aws-cron-parser#6]
You have a very nice d.ts file there which should work perfectly. Unfortunately, it does not seem to be packaged and is not in my node_modules. Meaning that I cannot use it and still have to copy the file manually to get this module to work in TypeScript.

**Comment by vinhtnguyen** [comment]
Hello Micheal! Thank you for reporting the issue. I have converted the code to TypeScript. The typings should work properly now. Thanks again!
