### ISSUE TITLE
some cases not working properly.

### ISSUE THREAD

**Issue by HCharlie** [beemhq/aws-cron-parser#7]
some cases could not be parsed:
1. `10 7/5 7 * ? 2020` will report error, but `10 7/5 7-9 * ? 2020` will not.
2. `10 7/5 ? * Wed-Fri 2020` will report error, but `10 7/5 ? * WED-FRI 2020` will not.

for the second, although the documents don't mention `Wed`, but it's work in the console.

some cases could not report error:
1.`10 7/5 * * Fri 2020`
2.`10 7/5 * * FRI 2020`
3.`10 7/5 * * 5 2020`
basically no ? on both dayOfMonth and dayOfWeeks field is allowed.

**Comment by vinhtnguyen** [comment]
Hello HCharlie. Thank you for reporting the issues to help us make this tool work properly!

I don't know what was wrong, but with the latest version, all 4 cron expressions can be parsed and next occurrence generated correctly. Perhaps we fixed the issue already.
- `10 7/5 7 * ? 2020`
- `10 7/5 7-9 * ? 2020`
- `10 7/5 ? * Wed-Fri 2020`
- `10 7/5 ? * WED-FRI 2020`

As for reporting the error when the cron expression is invalid, please note that it's our intention to not validate the cron expression. We intended the main functionality of our tool is to take the cron expression from CloudWatch and then generate the next occurrences. As a result, the cron expression is assumed to be validated by AWS already.

Regards,
Vinh
