### ISSUE TITLE
Some cases not working properly

### ISSUE THREAD

**Issue by anilkrishnach** [beemhq/aws-cron-parser#8]
These following cases are not getting parsed, but working in AWS Console.

1. `0 */3 */1 * ? *`
2. `15 12 ? * sun,mon *`

**Comment by vinhtnguyen** [comment]
Hello Anil,

Thank you for reporting the issues. I was not handling these crons correctly. Your report really helps us make this tool better for everyone. I have fixed this issue as of version 1.1.7.

Regards,
Vinh
