### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by abilani** [beemhq/aws-cron-parser#9]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: \node_modules\aws-cron-parser\built\index.js
require() of ES modules is not supported.
require() of node_modules\aws-cron-parser\built\index.js from D:\projects\relife-admin-panel-backend\.webpack\service\src\Modules\System\controllers\system.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\projects\relife-admin-panel-backend\node_modules\aws-cron-parser\package.json.

**Comment by steve-thousand** [comment]
I am having trouble working around this issue. Was there a solution found?

**Comment by vinhtnguyen** [comment]
Thank you for reporting this issue. I've investigated and fixed this issue with the new version 1.1.8.
You can use `const awsCronParser = require("aws-cron-parser");` for CommonJS (.cjs) code.
Or `import awsCronParser from "aws-cron-parser";` for ES Module (.mjs) code.
I've tested this with `node -v` v14.9.0 and it's working for me.
Thank you!
